684 cron architecture
betagouv/api-subventions-asso pull request #1164
Opened 2023-03-31 08:29 UTC by alice-telescoop

closes #684

2023-03-31 08:48 UTC, VSerain approved these changes

2023-03-31 08:48 UTC, VSerain commented on packages/api/src/modules/example/interfaces/cron/example.cron.controller.ts
> +const task = new Task("test", () => {
Tous nos contrôler sont des Classes, j'aimerais bien garder cette unité dans le code !

2023-03-31 08:48 UTC, VSerain commented on packages/api/src/modules/example/interfaces/cron/example.cron.controller.ts
> +const task = new Task("test", () => {
J'imaginais une interface genre : 
```
class TestCronCrontroller {

    @Cron({seconds: 2})
    updateData() {

    }

    @AsyncCron({ hours: 5})
    updateAsyncData(): Promise {
        return Promise.resolve();
    }
}
```

En plus ça te permettrai de mettre les mains dans les décorateurs ;)

2023-03-31 08:49 UTC, VSerain requested changes
J'ai approuve alors que je voulais comment ! Ducoup je suis obliger de mettre en request change pour enlver l'approuve :'(

2023-03-31 08:52 UTC, alice-telescoop commented on packages/api/src/modules/example/interfaces/cron/example.cron.controller.ts
> +const task = new Task("test", () => {
En effet joli :) je m'attaque à faire ça

2023-04-02 23:17 UTC, alice-telescoop commented
J'ai repris l'architecture avec les décorateurs que suggérait Victor. Il manque les tests mais vous pouvez déjà relire.

2023-04-03 07:52 UTC, mxmeunier approved these changes

2023-04-03 07:52 UTC, mxmeunier commented on packages/api/src/decorators/cronController.decorator.ts
> +                username: "Police du Cron",
🤣

2023-04-03 07:52 UTC, mxmeunier commented on packages/api/src/modules/example/interfaces/cron/example.cron.controller.ts
> +    @Cron({ seconds: 10 }, false)
On est d'accord que c'est TS qui traduit ces décorateurs et wrap les méthodes avec les méthodes associées ? Ou alors j'ai loupé l'info comme quoi c'était natif sur JS maintenant ?

2023-04-03 08:11 UTC, VSerain commented on packages/api/src/modules/example/interfaces/cron/example.cron.controller.ts
> +    @Cron({ seconds: 10 }, false)
Les décorateurs c'est du TS, je crois que c'est pas encore passer partout sur le JS vanilla

2023-04-07 08:13 UTC, VSerain commented on packages/api/src/cron.ts
> +    for (const controllerClass of controllers) {
Par convention une class devrait être ControllerClass

2023-04-07 08:17 UTC, alice-telescoop commented on packages/api/src/cron.ts
> +    for (const controllerClass of controllers) {
Je sais pas, vu que c'est une variable dynamique et pas une classe donnée

2023-04-07 08:17 UTC, VSerain approved these changes

2023-04-07 08:17 UTC, VSerain commented on packages/api/src/decorators/cronController.decorator.ts
> +export const errorHandler = cronName => {
Dans le futur, peut-être qu'on fera un genre de AdminNotifierService ou quelque choses du genre pour avoir des notifs sur plusieurs sujet ! Et aussi pour limitée la dépendence forte à mattermost dans un composant qui n'en a pas besoin ;) ! Mais pour un premier jet c'est top !

2023-04-07 08:19 UTC, VSerain commented on packages/api/src/cron.ts
> +    for (const controllerClass of controllers) {
Oui, mais pour moi, on sait que c'est une class on a juste pas le nom ! Et je trouve justement que c'est encore plus pertinent, car au premier coup d'œil ont ce dit "Tiens c'est un class" plutôt que "est-ce que c'est la class ou bien son instance" !

2023-04-07 08:51 UTC, alice-telescoop commented on packages/api/src/cron.ts
> +    for (const controllerClass of controllers) {
done

2023-04-07 08:55 UTC, merged