feat(api): add osiris actions evaluation
betagouv/api-subventions-asso pull request #118
Opened 2022-03-28 09:19 UTC by mxmeunier

2022-03-28 13:14 UTC, VSerain requested changes
Pas mal des retours sont plus liés à mon vieux code qu'à tes modifications, si c'est relou tu me dis et je ferais les changements.

Et bien jouée pour cette première PR qui clean déjà plein de truc ;)

2022-03-28 13:14 UTC, VSerain commented on packages/api/.gitignore
> +.DS_Store
Pas forcément dans cette PR, mais je me demande si on peut pas rassembler tous les gitignore à la racine du mono repo

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/associations/associations.service.ts
> +import { Siren, DefaultObject,  Rna, ProviderValues} from "../../@types";
Manque un espace après ProviderValues

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/demandes_subventions/interfaces/DemandeSubvention.ts
> +import {ProviderValue} from "../../../@types";
```suggestion
import { ProviderValue } from "../../../@types";
```

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/associations/associations.service.ts
> +import { Siren, DefaultObject,  Rna, ProviderValues} from "../../@types";
```suggestion
import { Siren, DefaultObject,  Rna, ProviderValues } from "../../@types";
```

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/etablissements/interfaces/Etablissement.ts
> +import {ProviderValues, Siret, DefaultObject} from "../../../@types";
```suggestion
import { ProviderValues, Siret, DefaultObject } from "../../../@types";
```

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/providers/chorus/interfaces/cli/chorus.cli.controller.ts
> +import { CliStaticInterface} from "../../../../../@types";
```suggestion
import { CliStaticInterface } from "../../../../../@types";
```

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
> +import { CliStaticInterface} from "../../../../../@types";
```suggestion
import { CliStaticInterface } from "../../../../../@types";
```

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/providers/leCompteAsso/interfaces/cli/leCompteAsso.cli.contoller.ts
> +import { CliStaticInterface} from "../../../../../@types";
```suggestion
import { CliStaticInterface } from "../../../../../@types";
```

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/providers/osiris/interfaces/cli/osiris.cli.contoller.ts
> +import { CliStaticInterface, Rna, Siret} from "../../../../../@types";
```suggestion
import { CliStaticInterface, Rna, Siret } from "../../../../../@types";
```

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/providers/osiris/osiris.parser.ts
> +            const data: DefaultObject<DefaultObject<string|number>> = OsirisParser.rawToRawWithHeaders(headers, raw, OsirisEvaluationEntity.defaultMainCategory);
On devrait définir DefaultObject<DefaultObject<string|number>> comme output de rawToRawWithHeaders, ça éviterai de le faire 3 dans le fichier.

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/providers/osiris/osiris.parser.ts
> +            return entity;
On peut juste faire un return new OsirisBlabla

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/user/interfaces/cli/user.cli.controller.ts
> +import { CliStaticInterface} from "../../../../@types";
```suggestion
import { CliStaticInterface } from "../../../../@types";
```

2022-03-28 13:14 UTC, VSerain commented on packages/api/src/modules/versements/interfaces/Versement.ts
> +import {ProviderValue, Siret} from "../../../@types";
```suggestion
import { ProviderValue, Siret } from "../../../@types";
```

2022-03-28 13:14 UTC, VSerain commented on packages/api/tests/modules/osiris/osiris.parser.test.ts
> +            console.log(actual, expected);
Supprimer le console.log

2022-03-28 13:14 UTC, VSerain commented on packages/api/tests/modules/osiris/osiris.service.test.ts
> +                const actual = (await osirisService.addEvaluation(expected));
Pas besoin de parenthèse

2022-03-28 13:14 UTC, VSerain commented on packages/api/tests/modules/osiris/osiris.service.test.ts
> +                const evaluation = (new OsirisEvaluationEntity({osirisActionId: "FAKE_OSIRIS_ID", siret: "WRONG_SIRET", evaluation_resultat: ""}, {}));
Pas besoin de parenthèse

2022-03-28 13:14 UTC, VSerain commented on packages/api/tests/modules/osiris/osiris.service.test.ts
> +                const evaluation = (new OsirisEvaluationEntity({osirisActionId: "FAKE_OSIRIS_ID", siret: "WRONG_SIRET", evaluation_resultat: ""}, {}));
Même chose pour ceux du dessous ;)

2022-03-28 13:41 UTC, mxmeunier commented on packages/api/.gitignore
> +.DS_Store
C'est vrai que je vais devoir le rajouter dans front et dto également

2022-03-29 07:23 UTC, VSerain commented on packages/api/.gitignore
> +.DS_Store
Bien je dirais que si on fait bien, le git ignore à la racine du projet, il doit pouvoir ignorer les infos des packages.

2022-03-30 06:22 UTC, mxmeunier commented on packages/api/.gitignore
> +.DS_Store
Je vais le retirer de API mais je suis pas sûr que si j'ouvre API directement dans vscode il sera pris en compte ! A tester. :)

2022-03-30 07:06 UTC, VSerain commented
N'oublie pas de mettre #close 51 dans la description de ta pr, pour lier le ticket !

2022-03-30 07:19 UTC, VSerain approved these changes

2022-03-30 07:29 UTC, merged