1309 richer signup
betagouv/api-subventions-asso pull request #1461
Opened 2023-06-27 16:00 UTC by alice-telescoop

closes #1309

2023-07-03 14:38 UTC, VSerain requested changes
Bien chager la partie Role avant de merger ;)

2023-07-03 14:38 UTC, VSerain commented on packages/api/src/modules/user/interfaces/cli/user.cli.controller.ts
> -        if (!fs.existsSync(file)) {
Pense à supprimer fs et csvParse des imports

2023-07-03 14:38 UTC, VSerain commented on packages/api/src/modules/user/interfaces/cli/user.cli.controller.ts
> +            await userService.createUser({ email });
Je pense qu'on devrais modifier la commande pour prendre un nom et prenom, comme ça dans le futur on aura de + en + d'information

2023-07-03 14:38 UTC, VSerain commented on packages/api/src/modules/user/user.service.ts
> +        const { hashPassword: _hashPwd, ...userWithoutPassword } = user;
Est-ce qu'on devrais pas uttiliser le remondeSecrets ?

2023-07-03 14:38 UTC, VSerain commented on packages/api/src/modules/user/user.service.ts
> +        console.log({ userInServiceBefore: user });
Log !

2023-07-03 14:38 UTC, VSerain commented on packages/api/src/modules/user/user.service.ts
> +        console.log({ res });
Log

2023-07-03 14:38 UTC, VSerain commented on packages/api/src/modules/user/user.service.ts
> +        const res = {
Tu peux return directement l'objet ! Mais j'imagine que tu l'avais fait avant de rajouter des logs ;)

2023-07-03 14:38 UTC, VSerain commented on packages/api/src/modules/user/user.service.ts
> +            ...user,
Et ducoup on enleve pas le nom, prenom ?

2023-07-03 14:38 UTC, VSerain commented on packages/api/src/shared/helpers/StringHelper.ts
> +    return xss(unsafe, {
C'est une mauvaise raison de pas le faire, mais juste pour information svelte fait également un coup de clean la dessus ;) ! Mais ducoup par principe est-ce qu'on devrait pas le faire sur les emails également

2023-07-03 14:38 UTC, VSerain commented on packages/api/src/modules/user/user.service.ts
> +            roles: userObject.roles || [RoleEnum.user], // ensures proper type
/!\ ça ca créer une fail qui permetrai de sinscrire avec le role qu'on veut (Admin par exemple) ;)

2023-07-03 16:00 UTC, alice-telescoop commented on packages/api/src/modules/user/interfaces/cli/user.cli.controller.ts
> +            await userService.createUser({ email });
Oui mais on va pas l'utiliser en cli avec plein d'infos, si ?

2023-07-03 16:01 UTC, alice-telescoop commented on packages/api/src/shared/helpers/StringHelper.ts
> +    return xss(unsafe, {
les emails on les check par regex je pense que ça fait le taff

2023-07-04 14:44 UTC, alice-telescoop commented on packages/api/src/modules/user/user.service.ts
> +        const { hashPassword: _hashPwd, ...userWithoutPassword } = user;
non, c'est pour le login, le front a besoin du token qui serait retiré par `removeSecrets`

2023-07-04 14:44 UTC, alice-telescoop commented on packages/api/src/modules/user/user.service.ts
> +            roles: userObject.roles || [RoleEnum.user], // ensures proper type
Normalement c'est géré dans le signup maintenant. Dans le service on doit pouvoir faire ce qu'on veut

2023-07-04 15:09 UTC, VSerain commented on packages/api/src/modules/user/user.service.ts
> +            roles: userObject.roles || [RoleEnum.user], // ensures proper type
Le signup ne fait rien par rapport au role il prends ce qu'on lui donne et le fil à createUser

2023-07-05 07:45 UTC, alice-telescoop commented on packages/api/src/modules/user/user.service.ts
> +            roles: userObject.roles || [RoleEnum.user], // ensures proper type
Je l'ai changé depuis ton commentaire, maintenant il écrit le rôle en argument du `signup` avant de passer à `createUser`

2023-07-05 09:49 UTC, VSerain commented on packages/api/src/modules/user/user.service.ts
> +            roles: userObject.roles || [RoleEnum.user], // ensures proper type
Yes j'avais pas vu ! Maintenant tu n'a plus besoin du || [RoleEnum.user] ou bien ils faut supprimer le if plus haut

2023-07-05 12:16 UTC, alice-telescoop commented on packages/api/src/modules/user/user.service.ts
> +            roles: userObject.roles || [RoleEnum.user], // ensures proper type
done

2023-07-05 12:16 UTC, alice-telescoop commented
si c'est bon pour toi tu peux enlever le `request change`

2023-07-06 07:10 UTC, VSerain approved these changes

2023-07-06 07:21 UTC, alice-telescoop commented on packages/api/package.json
> +        "jest-mock-module": "^0.2.0",
Ah bien u, j'ai voulu essayer un module qui permettait de `spy` sur tout un module mais en laissant l'implémentation de base. Ça n'a pas marché comme je voulais je dois enlever ça

2023-07-06 07:57 UTC, alice-telescoop commented on packages/api/package.json
> +        "jest-mock-module": "^0.2.0",
Je l'ai enlevé au rebase

2023-07-06 09:26 UTC, merged