feat(front): add modal on user deleted action
betagouv/api-subventions-asso pull request #1494
Opened 2023-07-11 13:58 UTC by VSerain

close #1477

2023-07-12 07:49 UTC, mxmeunier requested changes

2023-07-12 07:49 UTC, mxmeunier commented on packages/front/svelte/views/user/profile/components/ConfirmDeleteUserModal.svelte
> +            <Button styleClass="fr-col-offset-1" ariaControls="fr-modal">Annuler</Button>
pardon ?(!) c'est une classe de layout à mettre sur une div pas sur un bouton ! Quel est l'objectif ? utilise un gap sur la div du dessus si c'est pour séparer les deux boutons ou alors imbrique les boutons dans un `div`ou tu définis la classe `fr-col`

2023-07-12 07:49 UTC, mxmeunier commented on packages/front/svelte/dsfr/Button.svelte
> +     ${getSpecificIconClass()} ${styleClass}`;
pas fan on a pas le "droit" de modifier le style d'un composant DSFR

2023-07-13 13:22 UTC, VSerain commented on packages/front/svelte/views/user/profile/components/ConfirmDeleteUserModal.svelte
> +            <Button styleClass="fr-col-offset-1" ariaControls="fr-modal">Annuler</Button>
Alors déjà tu me dit pas pardon comme ça

2023-07-13 13:23 UTC, VSerain commented on packages/front/svelte/views/user/profile/components/ConfirmDeleteUserModal.svelte
> +            <Button styleClass="fr-col-offset-1" ariaControls="fr-modal">Annuler</Button>
Bon d'accord j'ai foirée je voulais juste ne pas que mes boutons ce colle

2023-07-13 13:23 UTC, VSerain commented on packages/front/svelte/dsfr/Button.svelte
> +     ${getSpecificIconClass()} ${styleClass}`;
Oui maitre !

2023-07-14 06:20 UTC, mxmeunier commented on packages/front/svelte/views/user/profile/components/ConfirmDeleteUserModal.svelte
> +            <Button styleClass="fr-col-offset-1" ariaControls="fr-modal">Annuler</Button>
I know ! ;)

2023-07-14 09:07 UTC, merged