872 form inputs unique
betagouv/api-subventions-asso pull request #1508
Opened 2023-07-17 13:30 UTC by alice-telescoop

closes #872

2023-07-18 05:00 UTC, mxmeunier approved these changes

2023-07-18 09:00 UTC, VSerain commented on packages/front/package.json
> +        "nanoid": "^4.0.2",
On à déjà la lib crypto qui permet de faire de la génération de string aléatoire

2023-07-18 11:48 UTC, mxmeunier commented on packages/front/svelte/dsfr/Input.svelte
> +    export let id = nanoid(7);
C'est une bonne pratique surtout si tu as plusieurs input gérés par des frameworks car ils se perdent et tu peux avoir des problèmes de réactivité (genre tu tape dans un et ça met à jour l'autre également)

2023-07-18 13:44 UTC, VSerain commented on packages/front/svelte/dsfr/Input.svelte
> +    export let id = nanoid(7);
Mouai le front c'est vraiment NAZE :D

2023-07-18 13:44 UTC, alice-telescoop commented on packages/front/svelte/dsfr/Input.svelte
> +    export let id = nanoid(7);
Et il faut un id pour un input afin de lier au label et cette liaison est importante pour l'accessibilité

2023-07-18 14:56 UTC, VSerain requested changes
Juste pour l'histoire de nanoid vs crypto

2023-07-18 15:42 UTC, alice-telescoop commented on packages/front/package.json
> +        "nanoid": "^4.0.2",
On n'utilise pas du tout `crypto`
`crypto` est + lourd alors que `nanoid` est spécialisée
`nanoid` était déjà une dépendance de `css-loader`
=> Je propose de sortir `crypto` et de garder `nanoid` sur le front

2023-07-18 15:46 UTC, alice-telescoop commented on packages/front/package.json
> +        "nanoid": "^4.0.2",
(j'ai fait le commit)

2023-07-19 05:33 UTC, mxmeunier commented on packages/front/package.json
> +        "nanoid": "^4.0.2",
yep nanoid est pas lourd je valide

2023-07-19 07:31 UTC, VSerain approved these changes

2023-07-19 07:31 UTC, merged