1839 validate and filter new chorus entity
betagouv/api-subventions-asso pull request #1882
Opened 2023-11-16 13:14 UTC by mxmeunier

Close #1839

2023-11-20 14:59 UTC, alice-telescoop commented on packages/api/src/modules/providers/chorus/__fixutres__/ChorusFixtures.ts
renommer le dossier `fixutres` -> `fixtures`

2023-11-20 14:59 UTC, alice-telescoop commented on packages/api/src/shared/helpers/DateHelper.ts
> +export const addDaysToDate = (date, nbOfDays = 1) => new Date(new Date(date).setDate(date.getDate() + nbOfDays));
pourquoi ça ne suffit pas avec un constructeur en moins ?
```suggestion
export const addDaysToDate = (date, nbOfDays = 1) => new Date(date).setDate(date.getDate() + nbOfDays);
```

2023-11-20 14:59 UTC, alice-telescoop commented on packages/api/src/shared/Validators.test.ts
>          });
🤩

2023-11-20 14:59 UTC, alice-telescoop commented on packages/api/src/modules/providers/chorus/chorus.parser.ts
> +    }
C'est pas nouveau mais je comprends pas bien cette histoire de `CODE`

2023-11-20 14:59 UTC, alice-telescoop commented on packages/api/src/modules/providers/chorus/chorus.parser.ts
> +    }
c'est joli :)

2023-11-21 08:08 UTC, mxmeunier commented on packages/api/src/shared/helpers/DateHelper.ts
> +export const addDaysToDate = (date, nbOfDays = 1) => new Date(new Date(date).setDate(date.getDate() + nbOfDays));
Parce que setDate ne renvoi pas une date mais un entier représentant le nombre de milliseconde.

C'est soit ça soit on écrit comme ceci :

```js
const newDate = new Date(date);
newDate.setDate(newDate.getDate());
return newDate
```

2023-11-21 08:09 UTC, mxmeunier commented on packages/api/src/shared/Validators.test.ts
>          });
ahah j'ai bombardé ^^

2023-11-21 08:11 UTC, mxmeunier commented on packages/api/src/modules/providers/chorus/chorus.parser.ts
> +    }
Alors Victor m'a expliqué et c'est juste une bidouille du format du XLSX qui a des headers vide par moment qui représentent toujours le même schéma :

En gros la première colonne a un header et la seconde est vide. La première colonne concerne le code et la seconde de label associé. Ce qu'on fait c'est qu'on renomme le premier header en "LABEL + CODE" et on renomme le second header (vide) par "LABEL"

2023-11-21 08:12 UTC, mxmeunier commented on packages/api/src/modules/providers/chorus/chorus.parser.ts
> +    }
Merci :) ça se rapproche de la programmation fonctionnelle ! Une autre façon d'aborder le code

2023-11-21 08:13 UTC, alice-telescoop commented on packages/api/src/shared/helpers/DateHelper.ts
> +export const addDaysToDate = (date, nbOfDays = 1) => new Date(new Date(date).setDate(date.getDate() + nbOfDays));
ok je pensais pas ; mais du coup va pour ça

2023-11-21 08:14 UTC, mxmeunier commented on packages/api/src/shared/helpers/DateHelper.ts
> +export const addDaysToDate = (date, nbOfDays = 1) => new Date(new Date(date).setDate(date.getDate() + nbOfDays));
oui et c'est nul parce que 1) ça modifie quand même la date 2) ça renvoi pas la date :/

2023-11-21 09:43 UTC, VSerain requested changes

2023-11-21 09:43 UTC, VSerain commented on packages/api/src/modules/providers/chorus/chorus.parser.ts
> +    }
Oui c'est tous à fait ça ! C'est lier à leurs fichers

2023-11-21 09:43 UTC, VSerain commented on packages/api/src/modules/providers/chorus/chorus.parser.ts
> +            .map(row => ({ parsedData: ParseHelper.linkHeaderToData(headers, row) }))
En revanche garder le découpage en petit fonction est top ! on comprends bien mieux ce que l'ont veux faire

2023-11-22 09:28 UTC, alice-telescoop reviewed
et je crois que le dossier des fixtures s'appelle encore `fixutres` ave la typo

2023-11-22 10:11 UTC, VSerain approved these changes

2023-11-24 08:49 UTC, alice-telescoop approved these changes

2023-11-28 13:37 UTC, VSerain commented on packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.test.ts
> +        afterAll(() => (ApiAssoDtoAdapter.formatEstablishementSiret = originalFormatEstablishementSiret));
On peut pas faire un truc genre mockReset

2023-11-28 14:09 UTC, alice-telescoop commented on packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.test.ts
> +        afterAll(() => (ApiAssoDtoAdapter.formatEstablishementSiret = originalFormatEstablishementSiret));
Je crois que non parce que c'est des méthodes statiques mais je ne suis pas sûre

2023-12-04 09:45 UTC, VSerain commented on packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.test.ts
> +        afterAll(() => (ApiAssoDtoAdapter.formatEstablishementSiret = originalFormatEstablishementSiret));
Hummm, ça reste quand même un obj non ?

2023-12-04 10:02 UTC, mxmeunier commented on packages/api/src/modules/providers/apiAsso/adapters/ApiAssoDtoAdapter.test.ts
> +        afterAll(() => (ApiAssoDtoAdapter.formatEstablishementSiret = originalFormatEstablishementSiret));
Pas possible de mock le méthode statique avec Jest.mock quand elles sont appelées depuis une autre méthode. La seule façon c'est d'explicitement remplacer la méthode sur l'object lui même (puis de remettre gentillement à sa place pour les tests futurs)

2023-12-07 11:33 UTC, alice-telescoop commented on packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.test.ts
> +            }
Je trouve pas clair cette tournure de code. Ça paraît bizarre que tu lèves une exception comme ça (même si je finis par comprendre que c'est pour être sûr d'entrer dans le `catch`)
```suggestion
            try {
                await chorusLineRepository.insertMany([]);
            } finally {
                            expect(mockedMongoHelper.buildDuplicateIndexError).toHaveBeenCalledWith(MONGO_SERVER_ERROR);
            }
```
?

2023-12-07 11:33 UTC, alice-telescoop commented on packages/api/src/modules/providers/chorus/chorus.service.ts
> +                duplicates = ((e as DuplicateIndexError).duplicates as ChorusLineEntity[]).length;
avec ce code-là tu n'auras jamais la fin du batch, si ?

2023-12-07 11:34 UTC, mxmeunier commented on packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.test.ts
> +                throw new Error("Error should have been throwned");
oh yes je me disais que ça sonnait faux `throwned`

2023-12-07 11:35 UTC, mxmeunier commented on packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.test.ts
> +            }
ah mais oui voilà ce que je cherchais ! j'avais oublié ce bon vieux `finally`. Merci, je change ça demain

2023-12-08 08:10 UTC, mxmeunier commented on packages/api/src/modules/providers/chorus/repositories/chorus.line.repository.test.ts
> +            }
Ne fonctionne pas car il faut quand même un catch pour rattraper l'erreur. Je fais un mix

2023-12-08 09:35 UTC, VSerain commented on packages/api/src/dataProviders/db/rnaSiren/rnaSiren.port.ts
> +            if (e instanceof MongoServerError && isDuplicateError(e)) {
C'est du detail mais on pourrai faire le Instanceof dans le isDuplicateError

2023-12-08 09:58 UTC, VSerain commented on packages/api/src/shared/helpers/MongoHelper.ts
> +    return ["E11000", "11000", 11000].includes(code);
<3

2023-12-08 10:07 UTC, mxmeunier commented on packages/api/src/dataProviders/db/rnaSiren/rnaSiren.port.ts
> +            if (e instanceof MongoServerError && isDuplicateError(e)) {
oui j'y avais pensé aussi mais bon ce sera pour une prochaine fois

2023-12-08 10:08 UTC, mxmeunier commented on packages/api/src/modules/providers/chorus/chorus.service.ts
> +        if (sirenIsAsso) return true;
ça change pas grand chose ! et c'est plus descriptif ainsi, non ?

2023-12-08 10:10 UTC, VSerain commented on packages/api/src/modules/providers/chorus/chorus.service.ts
> +        if (sirenIsAsso) return true;
Mouai ! ça va que tu par en vac :)

2023-12-08 10:21 UTC, mxmeunier commented on packages/api/src/modules/providers/chorus/chorus.service.ts
> +        if (sirenIsAsso) return true;
en fait c'était déjà comme ça ! :O

2023-12-08 10:21 UTC, mxmeunier commented on packages/api/src/modules/providers/chorus/chorus.service.ts
> +        if (sirenIsAsso) return true;
mais effectivement on peut retourner simplement `sirenIsAsso`

2023-12-08 10:21 UTC, mxmeunier commented on packages/api/src/shared/helpers/MongoHelper.ts
> +export const isDuplicateError = error => {
On est déjà dans le MongoHelper ?

2023-12-08 10:29 UTC, alice-telescoop commented on packages/api/src/shared/helpers/MongoHelper.ts
> +export const isDuplicateError = error => {
J'imagine quand on l'utilise ailleurs c'est + lisible :shrug:

2023-12-08 12:07 UTC, merged