61 provider route
betagouv/api-subventions-asso pull request #206
Opened 2022-05-05 07:53 UTC by mxmeunier

Close #61

2022-05-05 15:35 UTC, VSerain requested changes
Je ne me souviens plus pourquoi tu as déplacé le RNA Siren dans open-data ?

Dans postman il n'y a pas d'URL prédéfini si tu peux mettre à jour !

2022-05-05 15:35 UTC, VSerain commented on packages/api/src/modules/mail-notifier/providers/provider-factory.ts
> +import IProvider from "./@types/INotifier";
Ici aussi ;)

2022-05-05 15:36 UTC, VSerain commented on packages/api/src/modules/providers/datagouv/datagouv.service.ts
> +    provider = {
https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/

Fichier : Fichier StockUniteLegale

2022-05-06 07:44 UTC, mxmeunier commented on packages/api/src/modules/mail-notifier/providers/nodemailer.provider.ts
> +import IProvider from "./@types/INotifier";
Ah bien vu je n'ai changé que le nom du fichier !

2022-05-06 07:49 UTC, mxmeunier commented on packages/api/src/modules/providers/datagouv/datagouv.service.ts
> +    provider = {
En gros c'est un RAW mais en ligne ?

2022-05-06 07:55 UTC, VSerain commented on packages/api/src/modules/providers/datagouv/datagouv.service.ts
> +    provider = {
C'est un raw, juste au lieu que quelqu'un nous le transmette, c'est accessible en ligne oui !

2022-05-06 09:31 UTC, merged