Documents API ASSO
betagouv/api-subventions-asso pull request #207
Opened 2022-05-05 15:02 UTC by VSerain

Close #190

2022-05-06 09:49 UTC, mxmeunier commented
<img width="604" alt="Capture d’écran 2022-05-06 à 11 47 15" src="https://user-images.githubusercontent.com/7630775/167108779-a5a28d5c-b8c5-4474-b7a1-01d267dc0a28.png">

Au bûché !

2022-05-06 09:49 UTC, mxmeunier requested changes
Le code coverage est pas assez bon sur ton document.service :)

<img width="604" alt="Capture d’écran 2022-05-06 à 11 47 15" src="https://user-images.githubusercontent.com/7630775/167108917-d97beac4-dafa-42b3-a445-c914c6e11165.png">

2022-05-12 07:16 UTC, mxmeunier requested changes

2022-05-12 07:16 UTC, mxmeunier commented on packages/api/src/modules/documents/documents.service.test.ts
> +    describe("getDocumentBySiren", () => {
Tu ne test jamais les méthodes privées (aggregate, getDocumentProviders, etc) puisque tu les mocks toujours. Il faudrait au moins un test qui les exécute (ou alors on test vraiment les méthodes privée unitairement...)

2022-05-12 07:16 UTC, mxmeunier commented on packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
> +    private async findFullScopeAssociation(identifier: AssociationIdentifiers): Promise<{ associations: Association[], etablissements: Etablissement[], documents: Document[]} | null> {
Tests unitaires sur apiAsso.service ?

2022-05-16 07:16 UTC, VSerain commented on packages/api/src/modules/documents/documents.service.test.ts
> +    describe("getDocumentBySiren", () => {
Bien si justement :D https://github.com/betagouv/api-subventions-asso/pull/207/files#diff-dc8d6cad8c90eda60fd96cdebe17ef079c48164835956bba7d108229526a6f0dR241

2022-05-16 08:18 UTC, mxmeunier commented on packages/api/src/modules/documents/documents.service.test.ts
> +    describe("getDocumentBySiren", () => {
ah oui ^^'

2022-05-16 15:22 UTC, VSerain commented on packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
> +    private async findFullScopeAssociation(identifier: AssociationIdentifiers): Promise<{ associations: Association[], etablissements: Etablissement[], documents: Document[]} | null> {
Minute papillon !

2022-05-16 15:22 UTC, VSerain commented on packages/api/src/modules/providers/apiAsso/apiAsso.service.ts
> +    private async findFullScopeAssociation(identifier: AssociationIdentifiers): Promise<{ associations: Association[], etablissements: Etablissement[], documents: Document[]} | null> {
100% de coverage mon pti mesieur

2022-05-18 08:06 UTC, mxmeunier approved these changes

2022-05-18 08:11 UTC, merged