248 update fonjep import
betagouv/api-subventions-asso pull request #256
Opened 2022-05-23 11:55 UTC by mxmeunier

Close #248

2022-05-23 14:48 UTC, VSerain requested changes
Il te manque une petite migration pour mettre la bonne date aux données actuelle

2022-05-23 14:48 UTC, VSerain commented on packages/api/src/modules/providers/fonjep/adapters/FonjepEntityAdapter.ts
> +            pluriannualite: toProviderValue("Oui"),
Dans le futur je me demande si on ne devrait pas uniformiser les oui non cotés api et retournée un booléen

2022-05-23 14:48 UTC, VSerain commented on packages/api/src/modules/providers/fonjep/adapters/FonjepEntityAdapter.ts
> +            dispositif: toProviderValue("Fonjep"),
On pourrait utiliser les PROVIDER_NAME

2022-05-23 14:48 UTC, VSerain commented on packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
> +    protected async _parse(file: string, logs: unknown[], exportDate: string) {
Et est-ce qu'on devrait vérifier si la date est bien valide ?

2022-05-23 14:48 UTC, VSerain commented on packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
> +    protected async _parse(file: string, logs: unknown[], exportDate: string) {
Ou au moin afficher la date en gros genre Date d'export : TA DATE comme ça tu peut voir si tu tes pas foiré

2022-05-24 09:46 UTC, mxmeunier commented on packages/api/src/shared/CliController.ts
> +        if (!exportDate) exportDate = new Date().toISOString();
Export date est optionnelle, non ?

2022-05-24 09:48 UTC, mxmeunier commented on packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
> +    protected async _parse(file: string, logs: unknown[], exportDate: string) {
else exportDate = new Date(exportDate).toISOString(); va throw une erreur de lui même si la date est pas valide

2022-05-24 09:49 UTC, mxmeunier commented on packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
> +    protected async _parse(file: string, logs: unknown[], exportDate: string) {
Et le format de date c'est n'importe quel format string valide, mais je peux ajouter "YYYY-DD-MM"

2022-05-24 09:51 UTC, mxmeunier commented on packages/api/src/modules/providers/fonjep/adapters/FonjepEntityAdapter.ts
> +            pluriannualite: toProviderValue("Oui"),
C'est sûr que c'est mieux qu'un string Oui/Non

2022-05-24 09:54 UTC, VSerain commented on packages/api/src/shared/CliController.ts
> +        if (!exportDate) exportDate = new Date().toISOString();
Non je dirait qu'on le veux toujours , je pensais que le ? est-ai la pour une histoire d'heritage

2022-05-24 09:56 UTC, VSerain commented on packages/api/src/modules/providers/fonjep/adapters/FonjepEntityAdapter.ts
> +            pluriannualite: toProviderValue("Oui"),
Yes, c'est juste que la on sais quelle valeur ça prends dans les autres provider (coucou osiris) on a des oui, Oui, OUI, OuI, ....

2022-05-25 07:10 UTC, VSerain commented on packages/api/src/modules/providers/fonjep/interfaces/cli/fonjep.cli.controller.ts
> +    protected async _parse(file: string, logs: unknown[], exportDate: string) {
Yes je veux bien un mini commentaire ;)

2022-05-30 09:38 UTC, VSerain commented on packages/api/migrations/20220525083959-update-fonjep-import-date-and-add-templs-plein.js
> +        const cursor = db.collection("fonjep").find({});
Alors, si tu utilises la collection directement, le migrationManager n'a pas d'effet ! Ce que fait le migrationManager c'est quand dans un repository tu fais un get collection, il te retourne une collection dupliquée aux lieux de celle d'origine (Voirs migration repository). Donc soit tu passes par le repository fonjep pour tes accès à la db, soit tu passes directement via la db mais dans ce cas le nom de ta collection sera : fonjep-MIGRATION-DATABASE

2022-05-30 09:38 UTC, VSerain commented on packages/api/migrations/20220525083959-update-fonjep-import-date-and-add-templs-plein.js
> +        const cursor = db.collection("fonjep").find({});
Si tu passe directement par la db dans ce cas uttilise ta var fonjepCollection plutôt que de refaire un db.collection

2022-05-31 06:20 UTC, merged