2616 add update date to chorus dbo
betagouv/api-subventions-asso pull request #2625
Opened 2024-08-29 13:20 UTC by gcarra

2024-08-29 13:48 UTC, gcarra commented
Il faudrait modifier si les modifications que on voit par rapport au snapShot sont ok pour vous ? (Je ne connais pas très bien cette partie là de l'API)

2024-08-29 14:14 UTC, alice-telescoop requested changes
+ mettre à jour les snapshots du coup, cf msg mattermost

2024-08-29 14:14 UTC, alice-telescoop commented on packages/api/src/modules/providers/chorus/__fixtures__/ChorusFixtures.ts
Mauvaise idée de juste mettre `new Date()` dans une fixture parce que du coup la fixture change au cours du temps. Il vaut mieux figer une date arbitraire

2024-08-29 14:14 UTC, alice-telescoop commented on packages/api/src/modules/providers/chorus/adapters/ChorusAdapter.test.ts
> +                new Date(),
idem c'est pas mal de figer une date

2024-08-29 14:14 UTC, alice-telescoop commented on packages/api/tests/dataProviders/db/__fixtures__/chorus.fixtures.ts
> +        updated: new Date(),
idem

2024-08-29 14:47 UTC, gcarra commented on packages/api/src/modules/providers/chorus/__fixtures__/ChorusFixtures.ts
entendu, modifié.

2024-08-29 14:47 UTC, gcarra commented on packages/api/tests/dataProviders/db/__fixtures__/chorus.fixtures.ts
> +        updated: new Date(),
modifié

2024-08-29 14:48 UTC, gcarra commented on packages/api/src/modules/providers/chorus/adapters/ChorusAdapter.test.ts
> +                new Date(),
done

2024-08-30 07:50 UTC, alice-telescoop approved these changes

2024-08-30 08:01 UTC, merged