feat(front): move home page to svelte
betagouv/api-subventions-asso pull request #441
Opened 2022-09-21 09:39 UTC by VSerain

Close #403

2022-09-21 15:06 UTC, mxmeunier requested changes

2022-09-21 15:06 UTC, mxmeunier commented on packages/front/svelte/helpers/routeHelper.js
> +export function getQueryParams(url) {
Je viens de prendre connaissance de [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#browser_compatibility), c'est peut-être ce qu'il faut utiliser ici !

2022-09-21 15:06 UTC, mxmeunier commented on packages/front/svelte/views/home/Home.svelte
> +    const error = params.error;
Comme mis plus haut, peut-être utiliser URLSearchParam 

ici un code stack :

```
const params = new Proxy(new URLSearchParams(window.location.search), {
  get: (searchParams, prop) => searchParams.get(prop),
});
// Get the value of "some_key" in eg "https://example.com/?some_key=some_value"
let value = params.some_key; // "some_value"
```

2022-09-22 08:25 UTC, VSerain commented
Tu me valideras si ça te convient @mxmeunier

2022-09-26 14:09 UTC, mxmeunier approved these changes

2022-09-26 14:10 UTC, merged