fix(front, api): clean dauphin and subvention table
betagouv/api-subventions-asso pull request #472
Opened 2022-10-05 12:36 UTC by VSerain

Close #471

2022-10-05 13:35 UTC, mxmeunier requested changes

2022-10-05 13:35 UTC, mxmeunier commented on packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.ts
> +            serviceInstructeur = `Politique de la ville (Dept ${part[0]})`;
utiliser dispositif défini plus haut dans le template littéral

2022-10-05 13:35 UTC, mxmeunier commented on packages/front/svelte/views/association/components/SubventionTable.svelte
> +            <col class="col-120" />
ici tu supprime deux colonnes à dimension dynamique (calculé par le navigateur au rendu du tableau) pour remplacer par un à dimension fixe. As-tu vérifié sur 120+140 est égal à 100+espace restant ? (tu me parlais d'un pb graphique dans le tableau)

2022-10-05 13:35 UTC, mxmeunier commented on packages/front/svelte/views/association/components/SubventionTable.svelte
> +                        {valueOrHyphen(trim(element.subvention.dispositif, 53))}
par souci de refactoring et mise à jour on devrait enregistrer cette taille maximum de 53 quelque part car réutilisé plusieurs fois

2022-10-05 14:50 UTC, VSerain commented on packages/front/svelte/views/association/components/SubventionTable.svelte
> +                        {valueOrHyphen(trim(element.subvention.dispositif, 53))}
Bonne idée ! Je fait une var en haut

2022-10-05 15:00 UTC, VSerain commented on packages/front/svelte/views/association/components/SubventionTable.svelte
> +            <col class="col-120" />
Ba je sais pas ce que j'ai fait, mais ça à marcher :p ! On peut faire un point en vrai sur ce sujet ça sera plus simple je pense ;)

2022-10-06 12:24 UTC, mxmeunier commented on packages/api/src/modules/providers/dauphin/adapters/DauphinDtoAdapter.ts
> +            serviceInstructeur = `Politique de la ville (Dept ${part[0]})`;
Ça me va si c'est pas lié et que ça peu évoluer et devenir différent !

2022-10-06 12:25 UTC, mxmeunier commented on packages/front/svelte/views/association/components/SubventionTable.svelte
> +            <col class="col-120" />
Je vais essayer d'y penser pour voir si ça fonctionne miraculeusement ou pas (afin d'éviter de galérer à comprendre un potentiel bug graphique lié au tableau)

2022-10-06 12:26 UTC, mxmeunier approved these changes

2022-10-07 09:40 UTC, merged