618 etablissment documents
betagouv/api-subventions-asso pull request #713
Opened 2022-12-05 16:12 UTC by alice-telescoop

closes #618

2022-12-07 11:18 UTC, mxmeunier requested changes

2022-12-07 11:18 UTC, mxmeunier commented on packages/front/svelte/components/Documents/Documents.controller.js
> +        const promise = this.getterByType[this.resourceType](this.resource);
pourquoi ne pas exécuter ça dans le constructeur ? Je pense que si au montage du composant on a déjà une promise résolvée ça ne doit pas poser de problème pour le {#async} block

2022-12-07 11:18 UTC, mxmeunier commented on packages/front/svelte/helpers/providerValueHelper.js
> +        throw new Error("cannot aggregate metadata on non-object values");
à définir mais pour l'instant dans le front on ne throw pas d'Error. Je pense qu'il vaut mieux retourner providerValueObject sans traitement et éviter de bloquer l'application. Je sous entend qu'on a pas de try catch (par exemple dans documentService.getDocuments()). Et si jamais pour une raison x ou y l'api renvoie un type de données corrompue ça n'impactera pas toute l'app

2022-12-07 17:29 UTC, alice-telescoop commented
Pour les 3 autres commentaires j'ai testé un peu. En l'état, les documents ne sont chargés que lorsque l'onglet est ouvert. Quand j'ai essayé de mettre la promesse dans le constructeur (donc plus un store) j'ai deux cas pour deux tentatives :
- soit [sans unMount](https://github.com/betagouv/api-subventions-asso/files/10178467/dans_le_contructeur_sans_onMount.patch.txt) (ce que je pense que tu as fait), les documents sont chargés *avant* l'ouverture de l'onglet
- soit [en bidouillant pour passer un unMount](https://github.com/betagouv/api-subventions-asso/files/10178470/dans_contructeur_sans_avec_unMount.patch.txt) j'ai une erreur parce que documentPromise doit être défini pour que le composant soit monté

Si je garde comme la PR propose, les documents ne sont chargés qu'à l'ouverture de l'onglet, ce qui me paraît souhaitable, donc je laisse.

2022-12-08 09:09 UTC, mxmeunier approved these changes

2022-12-08 09:31 UTC, merged