feat(api): create mongodb migrations for association top stat
betagouv/api-subventions-asso pull request #734
Opened 2022-12-12 17:28 UTC by alice-telescoop

closes #668

2022-12-15 07:44 UTC, mxmeunier requested changes

2022-12-15 07:44 UTC, mxmeunier commented on packages/api/migrations/20221212101526-create-association-nb-requests-collection.js
> +                    identifier: { $regexFind: { input: "$meta.req.url", regex: /association\/([A-Za-z0-9]+)\/?$/ } }
Parce qu'il y a $ à la fin de la regex indique qu'on remonte toutes les routes contenant /association/:id donc aussi /search/association/:id ?

2022-12-15 07:44 UTC, mxmeunier commented on packages/api/migrations/20221212101526-create-association-nb-requests-collection.js
> +            { $project: { identifier: { $arrayElemAt: ["$identifier.captures", 0] } } },
Bon MongoDB n'étant pas mon fort, je suis plutôt preneur qu'une explication orale de tout ce que fait ce script côté BDD pour me faire à certains opérateur Mongo qui me sont encore inconnus / flou aujourd'hui. ;)

2022-12-15 07:44 UTC, mxmeunier commented on packages/api/src/modules/association-visits/associationVisits.service.ts
> +import { Association } from "@api-subventions-asso/dto";
On a déjà un module/stats. Il serait judicieux de regroupe tous les services liés au stats dans ce dossier.

On pourrait imaginer différents services qui seraient liés à plusieurs repository (pour éviter d'avoir trop de service).

Par exemple différencier les stats liées aux utilisateurs de celles liées aux associations/établissement, voir des requêtes en général.

On pourrait donc renommer l'actuel stats.service en stats.request.service (ou statsRequest, requestStats) et renommer ce associationVisits.service en association.service (ou structure.service si on pense inclure des potentielles stats liées aux établissement également).

2022-12-15 07:44 UTC, mxmeunier commented on packages/api/src/modules/association-visits/associationVisits.service.ts
> +    getTopAssociations(limit: number) {
si je ne m'abuse ne pas mettre de mot clé TS équivaut à "public" ? Si tel est le cas, rajouter public pour plus de cohérence avec la méthode registerRequest (ou alors supprimer public)

2022-12-15 07:44 UTC, mxmeunier commented on packages/api/src/modules/association-visits/repositories/associationVisits.repository.ts
> +    public async selectMostRequestsAssos(limit: number): Promise<AssociationTop[]> {
selectMostRequestedAssos ?

2022-12-15 07:44 UTC, mxmeunier commented on packages/api/src/modules/association-visits/repositories/associationVisits.repository.ts
> +    public updateAssoVisitCountByIncrement(name: string) {
updateAssoVisitCount ne suffit pas ?

2022-12-15 07:44 UTC, mxmeunier commented on packages/api/src/modules/associations/associations.service.ts
> +import assoVisitsRepository from "../association-visits/repositories/associationVisits.repository";
pas utilisé, à retirer

2022-12-15 07:44 UTC, mxmeunier commented on packages/api/src/modules/associations/interfaces/http/AssociationController.ts
> +                if (!req?.user?.roles?.includes("admin")) await associationVisitsService.registerRequest(association);
C'est au service d'avoir l'intelligence, le Controller n'est là que pour déléguer l'information. L'appel à `associationVisitsService.registerRequest`doit donc être fait dans `association.service.getAssociation()`

2022-12-15 07:50 UTC, mxmeunier requested changes

2022-12-15 07:50 UTC, mxmeunier commented on packages/api/migrations/20221212101526-create-association-nb-requests-collection.js
> +        const projectIdentifierPipeline = [
J'ai l'impression que toute la logique est dans la migration.

Mais elle devrait être dans un service, non ? Que se passera-t'il pour les futures recherches d'associations qui n'ont pas encore été recherchées actuellement, et donc pas enregistrer dans associationVisits ?

`associationVisits.repository.updateAssoVisitCountByIncrement()` ne fait que recherche les associations déjà en base si je ne me trompe

2022-12-15 08:16 UTC, alice-telescoop commented on packages/api/migrations/20221212101526-create-association-nb-requests-collection.js
> +                    identifier: { $regexFind: { input: "$meta.req.url", regex: /association\/([A-Za-z0-9]+)\/?$/ } }
Non, le `$`à la fin signifie que la chaîne de caractères s'arrête là. C'est parce qu'il *n'y a pas* `^` au début que la chaîne peut avoir `search`devant ou non. `^` signifie "début de chaîne" de la même façon que `$` signifie "fin de chaîne"

2022-12-15 08:18 UTC, alice-telescoop commented on packages/api/src/modules/association-visits/associationVisits.service.ts
> +import { Association } from "@api-subventions-asso/dto";
Aaaah, j'ai hésité et tout bougé >< J'ai eu du mal à voir si les services étaient plutôt liés aux routes ou aux collections mongo. J'ai fait comme ça parce que association-name avait son propre service, mais ça me va tout à fait de mettre ce code dans `stats.service`

2022-12-15 08:20 UTC, alice-telescoop commented on packages/api/src/modules/association-visits/repositories/associationVisits.repository.ts
> +    public updateAssoVisitCountByIncrement(name: string) {
J'ai l'impression que ça voudrait dire qu'on écrase avec une nouvelle valeur plutôt que d'incrémenter. J'avais pensé à `incrementAssoVisitCount` mais la dernière fois tu m'avais dit que ça devait prendre les noms des actions BDD. 

Ça m'embêterait qu'il n'y ait pas la notion d'incrément dans le nom et je ne sais pas trop comment le faire autrement.

2022-12-15 08:21 UTC, alice-telescoop commented on packages/api/src/modules/associations/interfaces/http/AssociationController.ts
> +                if (!req?.user?.roles?.includes("admin")) await associationVisitsService.registerRequest(association);
Là je suis pas trop d'accord, pour deux raisons
- ça dépend de qui fait la requête, qui est vraiment un info du scope du controller pour moi
- le service `getAssociation`me paraît plus générique, et pourrait être appelé par d'autres controller ou d'autres services. Or, c'est spécifiquement à l'appel de cette route qu'on veut enregistrer les requêtes

2022-12-15 08:23 UTC, alice-telescoop commented on packages/api/migrations/20221212101526-create-association-nb-requests-collection.js
> +        const projectIdentifierPipeline = [
La logique des anciennes assos est entièrement dans la migration, oui.

Par contre `associationVisits.repository.updateAssoVisitCountByIncrement()` crée les documents des associations qui ne sont pas déjà dans la collection, grâce à l'option `upsert`.

La logique qui est dans la migration est donc bien une logique qui ne s'exécutera qu'une seule fois.

2022-12-19 07:41 UTC, mxmeunier commented on packages/api/src/modules/stats/repositories/associationVisits.repository.ts
> +import { AssociationTop } from "packages/dto";
attention, pourquoi modifier ça sur cette PR ?

2022-12-19 07:48 UTC, mxmeunier commented on packages/api/src/modules/stats/stats.service.test.ts
> +                expect(repo).toHaveBeenCalledWith(expectedName, expectedDate);
Pourquoi expect.anything() ? Tu dois savoir la date qui est utilisée non ? Tu peux mock new Date() pour retourner toujours la même date par exemple. C'est pas très important ici mais tu ne t'assure pas que le second argument est bien une date !

2022-12-19 07:50 UTC, mxmeunier commented on packages/api/src/modules/stats/repositories/associationVisits.repository.ts
> +import { AssociationTop } from "packages/dto";
je crois que ça a été corrigé dans un prochain commit

2022-12-19 07:50 UTC, mxmeunier approved these changes

2022-12-19 08:27 UTC, alice-telescoop commented on packages/api/src/modules/stats/repositories/associationVisits.repository.ts
> +import { AssociationTop } from "packages/dto";
Oui le code final de la PR c'est celui avec @api-subventions-asso

2022-12-19 08:33 UTC, alice-telescoop commented on packages/api/src/modules/stats/stats.service.test.ts
> +                expect(repo).toHaveBeenCalledWith(expectedName, expectedDate);
J'utilise beaucoup cette fonction pour faire varier et tester le format du nom de l'asso dans l'objet "asso". Du coup ce n'est pas l'objet de ces utilisations de tester la date. Dans la PR finale il y a un autre test avec l'appel qui met un `expect.anything()` pour `expectedName` mais teste bien que la date est bonne. Je sépare juste les tests pour que ce soit vraiment très unitaire

2022-12-19 08:38 UTC, merged

2022-12-29 20:18 UTC, alice-telescoop commented
@VSerain @mxmeunier Je pense qu'il faut revert ça provisoirement parce que la migration n'est pas compatible mongo:4. Vous avez une méthodologie pour gérer ça ?

2022-12-30 09:00 UTC, VSerain commented
Je m'en occupe ! Tu peux réouvrire le ticket qui correspond et le passer dans le sprint courant, pour qu'on le reprenne / re détail si besoin ! Ok pour toi ?

2022-12-30 09:08 UTC, alice-telescoop commented
J'ai pas compris ce dont tu t'occupais. On peut en discuter vite fait en vocal peut-être ?

2022-12-30 09:09 UTC, VSerain commented
Yes !