653 widget top association
betagouv/api-subventions-asso pull request #781
Opened 2022-12-27 14:19 UTC by VSerain

Close #653

2022-12-27 15:08 UTC, mxmeunier commented on packages/front/svelte/components/Widget.svelte
> +    .widget__title {
au nom encore une nouvelle convention de nommage CSS :/

il va nous falloir réellement créer un document guidelines...

2022-12-27 15:08 UTC, mxmeunier commented on packages/front/svelte/resources/statistics/statistics.port.js
> +        const path = `${this.BASE_PATH}/associations?${toQueryString(query)}`;
Pourquoi un custom toQueryString(),alors qu'Axios propose un `options.params` qui est traduit en query après ?

2022-12-27 15:08 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +    <div class="fr-col-6">
je crois que sémantiquement il fait un fr-col-row au dessus d'un fr-col-*

2022-12-27 15:08 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +                <div class="top-associations_content">
Encore une autre nommage de classe CSS. Il faut qu'on se mette d'accord sur les classes de composant (`_` ou `__` ou `-` etc)

2022-12-27 15:08 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-weight: 500;
il doit y avoir une classe DSFR pour mettre font-weight: 500 non ?

2022-12-27 15:08 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-size: 16px;
idem pour le font-size si Marion a suivi le DSFR elle a du choisir un couple front/size qui doit se définir par une classe CSS du DSFR

2022-12-27 15:08 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +    _buildStartDate(endDate) {
Je me demande si on a pas déjà un Helper qui détermine la date 1 an avant la date donnée. Peut-être créer un Helper sinon ? Il me semble que plusieurs widget utilisent ça !

2022-12-27 15:18 UTC, VSerain commented on packages/front/svelte/components/Widget.svelte
> +    .widget__title {
Oui d'autant plus que si il y a un truc ou je suis pas à jours c'est l'archi et tous le trallala en css ! :D 
J'ai essayé de reprendre ce qui était fait dans Card par le dsfr !
Tu utilises quoi comme convention ?

2022-12-27 15:19 UTC, VSerain commented on packages/front/svelte/resources/statistics/statistics.port.js
> +        const path = `${this.BASE_PATH}/associations?${toQueryString(query)}`;
Parce que je reviens de vacances et que j'ai même pas pensée à vérifier :D

2022-12-27 15:19 UTC, VSerain commented on packages/front/svelte/resources/statistics/statistics.port.js
> +        const path = `${this.BASE_PATH}/associations?${toQueryString(query)}`;
Pour une fois que j'avais fait tous mes tests :D

2022-12-27 15:20 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +    <div class="fr-col-6">
C'est le cas mais dans un autre composant ! C'est tordu tu pense ?

2022-12-27 15:21 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +                <div class="top-associations_content">
Sinon, on fait tous en markdon fini les trucs classe et avec des belles couleurs, juste du noir et blanc !

2022-12-27 15:21 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-size: 16px;
Fichtre ! Satanée css, je regarde ça !

2022-12-27 15:24 UTC, VSerain commented on packages/front/.eslintrc
> +        "import/resolver": {
Pour pouvoir avec des imports moins long ! comme ça avec un @resources ou bien un @components on à direct access au bon dossier, ça evite les ../../../../../../ et aussi limite les soucis quand on déplace un fichier et que tous les imports sont pété :D

2022-12-27 15:27 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-size: 16px;
Comment tu fait pour retrouver les class css du dsfr ? Je trouve rien sur leurs site

2022-12-27 15:35 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +    _buildStartDate(endDate) {
Done

2022-12-29 09:44 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-size: 16px;
Oui c'est fait

2022-12-29 09:44 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-weight: 500;
Non j'ai pas trouver ;'(

2022-12-29 19:10 UTC, alice-telescoop commented on packages/front/svelte/components/Widget.svelte
> +    .widget__title {
J'ai pas en tête ce qu'il y a ailleurs dans notre code mais ça ressemble à du [BEM](https://alticreation.com/bem-pour-le-css/) qui est une convention assez répandue, mais qui peut être verbeuse

2022-12-29 19:27 UTC, alice-telescoop commented on packages/front/svelte/components/Widget.svelte
> +        margin-bottom: 24px;
en classe dsfr c'est `fr-mb-3w`, si ça peut alléger notre css

2022-12-29 19:27 UTC, alice-telescoop commented on packages/front/svelte/resources/statistics/statistics.service.test.js
> +            expect(actual).toBe(expected);
C'est volontaire de faire comme ça plutôt que `expect(portGetTopAssociationsMock).toBeCalled(1)` ?

2022-12-29 19:27 UTC, alice-telescoop commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +        this.startDateMonth = this._startDate.toLocaleString("default", { month: "short" });
À coordonner avec l'API mais là il y a un jour de trop : si on est le 11/04/2022 ça fera du 11/04/2021 au 11/04/2022 inclus alors qu'il faudrait partir du 12/04/2021

2022-12-29 19:27 UTC, alice-telescoop commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +        this.topAssociations.set(topAssociations);
C'est volontaire de masquer la fonction `_updateTopAssociations` ? Pourquoi ne pas lui donner un nom peut-être plus générique mais l'appeler directement et ne pas passer par `load`

2022-12-30 08:04 UTC, VSerain commented on packages/front/svelte/resources/statistics/statistics.service.test.js
> +            expect(actual).toBe(expected);
C'est une habitude qu'on a prise avec @mxmeunier !
Les deux sont valides ! On peut rediscuter de cette façon de faire pour le call à un mock

2022-12-30 08:08 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +        this.topAssociations.set(topAssociations);
C'est volontaire, car le composant svelte n'a pas à demander qu'on update, son job, c'est juste d'afficher ! Par contre, à un moment, j'avais tout mis dans load, mais je me suis dit qu'il fallait mieux découper ! Mais je peux tous remettre dans le load si tu trouve ça plus logique !

2022-12-30 08:08 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +        this.startDateMonth = this._startDate.toLocaleString("default", { month: "short" });
Bienvue !

2022-12-30 08:25 UTC, VSerain commented on packages/front/svelte/components/Widget.svelte
> +        margin-bottom: 24px;
Yes j'ai tous clean ici !

2022-12-30 08:26 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +        this.startDateMonth = this._startDate.toLocaleString("default", { month: "short" });
Fait !

2022-12-30 08:34 UTC, VSerain commented on packages/front/svelte/resources/statistics/statistics.service.test.js
> +            expect(actual).toBe(expected);
C'est bloquant pour toi ? Ou bien, je peux close et on en reparle tous les trois ?

2022-12-30 08:37 UTC, alice-telescoop commented on packages/front/svelte/resources/statistics/statistics.service.test.js
> +            expect(actual).toBe(expected);
Non pas bloquant ;)

2022-12-30 08:37 UTC, alice-telescoop commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +        this.topAssociations.set(topAssociations);
Pas bloquant non plus, ce n'est qu'une question de style

2022-12-30 09:25 UTC, VSerain commented
# NE PAS MERGER
STUCK par #668

2022-12-30 09:38 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +        this.topAssociations.set(topAssociations);
Ok, je rajoute ce point dans la liste des choses à discuter

2023-01-02 08:30 UTC, mxmeunier commented on packages/front/svelte/components/Widget.svelte
> +    .widget__title {
Je pense qu'il faut choisir un truc plus simple car avec Svelte + le DSFR on aura pas beaucoup de CSS. BEM c'est trop lourd et pas forcément accepté par la majorité de la communauté

2023-01-02 08:30 UTC, mxmeunier commented on packages/front/svelte/resources/statistics/statistics.port.js
> +        const path = `${this.BASE_PATH}/associations?${toQueryString(query)}`;
ahah dommage :D

2023-01-02 08:30 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +    <div class="fr-col-6">
Oui je pense qu'un seul composant doit gérer le layout. Si possible le parent d'ailleurs

2023-01-02 08:31 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-weight: 500;
Humm étrange je vais regarder

2023-01-02 08:38 UTC, VSerain commented on packages/front/svelte/components/Widget.svelte
> +    .widget__title {
Ok, j'ai rajouté ça dans les points qu'il faut que l'on discute

2023-01-02 09:09 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-weight: 500;
Comment à tu fais pour tester graphiquement sans l'implémentation de l'API ? Tu as créé à la main à tableau dans le front ? Je voulais essayer des classes DSFR pour voir si ça résout ce problème de font-weight défini à la main

2023-01-02 09:12 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-weight: 500;
Ba en faite au moment ou j'ai fait le dev, on avait l'implémentation dans l'api, on a dégager l'implé cotée api car elle ne fonctionnait pas avec le mongo de prod, c'est pour ça que le dev est repassé en draft

2023-01-02 09:12 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +        font-weight: 500;
Cela dit, il suffit que le statistique port retourne des fausses valeurs pour que tu puisses tester  !

2023-01-03 09:21 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.js
> +        this.topAssociations.set(topAssociations);
Renomée load en init

2023-01-17 09:14 UTC, alice-telescoop approved these changes

2023-01-17 12:04 UTC, mxmeunier commented on packages/front/svelte/resources/statistics/statistics.port.js
> +import axios from "axios";
`statistics` ça fait un peu verbeux non ? On utilise déjà `stats` côté API on devrait rester cohérent non ?

2023-01-17 12:04 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +    .justify-space-between {
à mettre dans global.css ?

2023-01-17 12:04 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.test.js
> +    describe("load", () => {
init

2023-01-17 12:06 UTC, mxmeunier requested changes

2023-01-17 12:06 UTC, mxmeunier commented on packages/front/svelte/components/Widget.svelte
> +<div class="widget fr-p-5v">
j'ai bien 32px de padding sur Figma donc 4w

2023-01-17 13:36 UTC, VSerain commented on packages/front/svelte/resources/statistics/statistics.port.js
> +import axios from "axios";
Chez pas, je me dis qu'on est pas à 5 caractères et que si non on fait Asso; Etab; Sub; Vers

2023-01-17 13:36 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +    .justify-space-between {
Oui, le nom te va ?

2023-01-17 13:37 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociationsController.test.js
> +    describe("load", () => {
Fichtre

2023-01-17 13:37 UTC, mxmeunier commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +    .justify-space-between {
c'est verbeux mais ça précise ce que ça fait (peut-être juste .space-between ?)

2023-01-17 13:37 UTC, VSerain commented on packages/front/svelte/resources/statistics/statistics.port.js
> +import axios from "axios";
@alice-telescoop, tu en penses quoi ?

2023-01-17 13:38 UTC, mxmeunier commented on packages/front/svelte/resources/statistics/statistics.port.js
> +import axios from "axios";
C'est juste que le path c'est déjà `/stats` c'est pour être cohérent. Aucun impact sur le code

2023-01-17 13:46 UTC, VSerain commented on packages/front/svelte/views/admin/stats/components/TopAssociations/TopAssociations.svelte
> +    .justify-space-between {
va pour space-between

2023-01-17 13:56 UTC, mxmeunier approved these changes

2023-01-17 14:07 UTC, alice-telescoop commented on packages/front/svelte/resources/statistics/statistics.port.js
> +import axios from "axios";
Ç'aurait pas été un problème de faire `statistics` mais on a déjà mis `stats` partout donc je penche pour `stats`

2023-01-18 14:17 UTC, VSerain commented on packages/front/svelte/resources/statistics/statistics.port.js
> +import axios from "axios";
Ok, je change !

2023-01-18 14:33 UTC, merged