feat(front): add user actif on admin view list
betagouv/api-subventions-asso pull request #784
Opened 2022-12-28 10:29 UTC by VSerain

Close #658

2022-12-29 06:29 UTC, mxmeunier requested changes

2022-12-29 06:29 UTC, mxmeunier commented on packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> -    import Button from "../../../../dsfr/Button.svelte";
Rajouter l'import du Button qui est utilisé plus bas

2022-12-29 08:10 UTC, VSerain commented on packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> -    import Button from "../../../../dsfr/Button.svelte";
Bienvue l'aveugle !

2022-12-29 19:42 UTC, alice-telescoop commented on packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> +    }
C'est encore un nouvel endroit avec le quick fix, il semble qu'il serait temps de faire le composant

2022-12-29 19:45 UTC, alice-telescoop commented
Je n'ose pas approve vu qu'il y avait change requested par ailleurs, mais j'ai quand même l'impression que ç'a été résolu

2022-12-30 08:49 UTC, VSerain commented on packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> +    }
Oui, on doit avoir une discutions avec Marion parce que normalement les tooltips son moyen ok avec de l'accessibilité ! On devrait pas du tout en avoir, c'est pour ça qu'on l'avait en cracra dans un composant !

2022-12-30 08:51 UTC, alice-telescoop commented on packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> +    }
J'ai bien compris ce contexte mais ça fait plusieurs fois qu'on en fait quand même et ça fait beaucoup de duplication à force. L'idée de discuter avec Marion ce serait que le design change ?

2022-12-30 08:52 UTC, VSerain commented
> Je n'ose pas approve vu qu'il y avait change requested par ailleurs, mais j'ai quand même l'impression que ç'a été résolu

Tu peux approuver si pour toi, c'est ok ! Je ne mergerai pas tant que maxime ne m'aura pas validé que c'était ok pour lui ;)

2022-12-30 09:41 UTC, VSerain commented on packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> +    }
Oui, c'est bien ça, on ne devrait pas du tout avoir de tooltip ! Mais tu as raison, je vais passer ça en composant !

2022-12-30 10:58 UTC, mxmeunier commented on packages/front/svelte/views/admin/users/composents/TableUsers.svelte
> +    }
Le seul endroit ou les tooltips sont "autorisés" c'est dans la partie admin en gros. Mais autant ne plus utiliser ce composant

2022-12-30 11:00 UTC, mxmeunier approved these changes

2022-12-30 11:00 UTC, merged