862 add user before year
betagouv/api-subventions-asso pull request #912
Opened 2023-01-20 08:38 UTC by VSerain

Closes #862 #867

2023-01-20 10:23 UTC, alice-telescoop requested changes
J'ai aussi un commentaire plus général sur comment on prend en compte la valeur des données avant le début de l'année. Sur la maquette on voir un peu d'info avant janvier donc je me demande si on ne veut pas afficher ce point là en plus, sans légende (c'est l'interprétation que j'ai de la maquette)

2023-01-20 10:23 UTC, alice-telescoop commented on packages/api/src/modules/stats/interfaces/http/StatsController.test.ts
>          };
À reprendre à la lumière de #902. En plus on voulait plutôt les index des mois que leurs noms

2023-01-20 10:23 UTC, alice-telescoop commented on packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.test.js
> +            const actual = await ctrl.dataPromise.value;
pourquoi l'`await` ? Ce test avait vocation à tester qu'on enregistrait bien la promesse elle-même

2023-01-20 10:23 UTC, alice-telescoop commented on packages/front/svelte/resources/stats/stats.service.js
> +        return statsPort.getMonthlyUserCount(year);
Cette modif n'était à faire que si c'était géré côté label et/ou côté api mais je ne vois pas cette gestion. En l'état ça va à nouveau envoyer des données fausses pour les mois futurs de l'année en cours, je crois

2023-01-20 10:29 UTC, VSerain commented on packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.test.js
> +            const actual = await ctrl.dataPromise.value;
Bien la value date dataPromise est une promise et vu qu'on compare avec expected qui elle est un simple obj

2023-01-20 10:30 UTC, VSerain commented on packages/front/svelte/resources/stats/stats.service.js
> +        return statsPort.getMonthlyUserCount(year);
Raf ! La vraie histoire, c'est que j'avais commencée à dégager la parte API qui fait ça ! Mais après je me suis dit non c'est pas pour cette pr, du coup, je suis revenue en arrière mais on dirait que j'ai oublier un truc !

2023-01-20 10:39 UTC, alice-telescoop commented on packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.test.js
> +            const actual = await ctrl.dataPromise.value;
J'ai mis un simple objet parce que c'était pour un mock. Dans le contexte on veut juste que `dataPromise` soit mis à jour avec le résultat du service, que ce soit une promesse ou non. C'est aussi pour ça que j'avais `mockReturnValue`

2023-01-20 10:44 UTC, VSerain commented on packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.test.js
> +            const actual = await ctrl.dataPromise.value;
Le mockReturnValue "mockai" pour tous les tests suivant c'est pour ça que j'ai mis un once !

2023-01-20 10:49 UTC, VSerain commented on packages/front/svelte/views/admin/users/composents/MonthlyUserCountByYear/MonthlyUserCountByYear.controller.test.js
> +            const actual = await ctrl.dataPromise.value;
Bienvue !

2023-01-24 13:25 UTC, alice-telescoop reviewed
petit clean et doute sur le format de donnée dans le test

2023-01-24 14:16 UTC, VSerain commented on packages/api/src/modules/stats/stats.service.test.ts
> +                December: 5
Alors ça c'est chelou

2023-01-24 14:36 UTC, VSerain commented
Voilà @alice-telescoop tout beau tout propre !

2023-01-24 14:42 UTC, alice-telescoop approved these changes

2023-01-25 13:47 UTC, merged